### ISSUE TITLE
Sale? Gerber files? 

### ISSUE THREAD

**Issue by raleighlittles** [medo64/CyberCard#1]
First off I wanted to say thanks for this project. I actually came across James' blog post several years ago and remarked at how neat it was, it's cool that there's finally a direct USB option.

I have a few questions:

Would you be open to selling pre-assembled kits? [Tindie](https://www.tindie.com/) is basically the standard marketplace for something like this, but even Etsy or Ebay could work.

If the answer to that question is no, then, would you be comfortable with at least providing the Gerber & BOM files so that people can order their own kits? Here's some [info on exporting Gerber files from diptrace](https://www.pcbway.com/blog/PCB_Layout_Software/How_to_generate_Gerber_files_from_DipTrace.html)

**Comment by medo64** [comment]
Hi,

I won't be making any pre assembled kits for sales. Mostly because CyberPower can change their design at any point in time and I am not going to invest time and money into testing it with their newer models. Project scratched my itch and that's was unfortunately all the time I was ready to sink into it.

That said, I made gerbers are available [for download](https://github.com/medo64/CyberCard/releases/tag/vD2204) if people don't want to deal with DipTrace.
